config/routes.rb
Rails.application.routes.draw do



# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  namespace :admin do
  resources :genres, :items, :customers, :orders, :order_details
  end
  
  get '/admin' => 'admin/homes#top'
  
    get '/orders/new' => 'public/orders#new', as: "orders_new"
    post '/orders/confirm' => 'public/orders#confirm', as: "orders_confirm"
    get '/orders/complete' => 'public/orders#complete', as: "orders_complete"
    get '/orders/:id' => 'public/orders#show', as: "orders_show"
    get '/orders' => 'public/orders#index', as: "orders_index"
    post '/orders' => 'public/orders#create', as: "orders_create"
    
    get '/cart_items' => 'public/cart_items#index'
    post '/cart_items' => 'public/cart_items#create'
    delete 'cart_items/:id' => 'public/cart_items#destroy', as: "destroy_cart_item"
    delete 'destroy_all' => 'public/cart_items#destroy_all', as: "destroy_all_cart_item"
    patch '/cart_items/:id' => 'public/cart_items#update', as: "update_cart_item"
    get '/items' => 'public/items#index'
    get '/items/:id' => 'public/items#show', as: "item_show"

    get '/addresses' => 'public/addresses#index'
    post '/addresses' => 'public/addresses#create'
    get '/addresses/:id/edit' => 'public/addresses#edit' ,as: "address"
    patch '/addresses/:id' => 'public/addresses#update', as: "update_address"
    delete '/addresses/:id' => 'public/addresses#destroy', as: "destroy_address"
  


  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'
  get '/customers/my_page' => 'public/customers#show', as: "my_page"
  get '/customers/information/edit' => 'public/customers#edit'
  patch '/customers/information' => 'public/customers#update'
  get '/customers/quit' => 'public/customers#quit'
  patch '/customers/out' => 'public/customers#out'

  
    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer, foreign_key: "customer_id"
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item, foreign_key: "item_id", optional: true
  belongs_to :customer, foreign_key: "customer_id", optional: true
  validates :amount, presence: true
  
def subtotal
    item.with_tax_price * amount
end



end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :addresses
  has_many :cart_items, dependent: :destroy
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :encrypted_password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :is_deleted, inclusion: {in: [true, false]}
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_one :item
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre, foreign_key: "genre_id", optional: true
  has_many :cart_items
  has_many :order_details
  attachment :image
  
 
  validates :image, presence: true
  validates :price, presence: true
  validates :genre_id, presence: true
  validates :is_active, inclusion: {in: [true, false]}
  
  def with_tax_price
      (price * 1.1).floor
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, foreign_key: "customer_id", optional: true
  has_many :order_details
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, finish_prepare: 4 }
 

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order, foreign_key: "order_id", optional: true
  belongs_to :item, foreign_key: "item_id", optional: true
  enum making_status: {
   production_not_possible: 0,
   production_pending: 1,
   in_production: 2,
   production_complete: 3
  }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  

  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page]).per(8)
    @order_details = OrderDetail.all
    @subamount = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def index
    @items = Item.page(params[:page])
    
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end
  
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @total = 0
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order_details = @order.order_details
    
    if @order.status == "confirm_payment"
      @order_details.update_all(making_status: 1)
    else  
      
    end

    redirect_to request.referer

  end
  
  
  private
  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name, :select_address, :address_id, :total_payment, :status)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#   before_action :configure_permitted_parameters, if: :devise_controller?
# before_action :authenticate_admin!, except: [:top, :about]
# before_action :authenticate_customer!, except: [:top, :about, :index]
#   protected

#   def configure_permitted_parameters
#     devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :encrypted_password, :address, :telephone_number, :is_deleted])
#   end

protected
  def after_sign_in_path_for(resource)
    if customer_signed_in?
        root_path
    else
      admin_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      admin_session_path
    else root_path
    end
  end

  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
  <div class="container">
    <p>ジャンル編集</p>
    <div class ="row">
      
      <%= form_with model: @genre ,url: admin_genre_path(@genre.id), method: :patch do |f| %>
      <div class="form-group">
        <%= f.label :ジャンル名, class: "mr-5" %>
        <%= f.text_field :name, class: "mr-5" %>
        <%= f.submit '変更を保存', class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
    

  </div>
    
  

app/views/admin/genres/index.html.erb
  <div class="container">
    <p>ジャンル一覧・追加</p>
    <div class="row">
      
      <%= form_with model: @genre, url: '/admin/genres', method: :post do |f| %>
      <div class="form-group">
        <%= f.label :ジャンル名, class: "mr-5" %>
        <%= f.text_field :name, class: "mr-5", value: ""  %>
        <%= f.submit '新規登録', class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
    
    <div class ="row">
      <div class="col-sm-5">
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>ジャンル</th>
              <th></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <% @genres.each do |genre| %>
          <tbody>
            <tr>
              <td><%= genre.name %></td>
              <td>
                <%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-sm btn-success" %>
              </td>
            </tr>
          </tbody>
          <% end %>
        </table>
        </div>
        <div class="col-sm-6"></div>
      </div>
  </div>
    

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-10">
      <p>注文履歴一覧</p>
      <table class="table-bordered col-12" cellpadding="10">
        <tr>
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
        <% @orders.each do |order| %>
        <tr>
          <td>
            <%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order) %>
          </td>
          <td>
            <%= order.name %>
          </td>
          <td>
            <% order.order_details.each do |order_detail| %>
              <% @subamount += order_detail.amount %>
              
            <% end %>
            <%= @subamount %>
            <% @subamount = 0 %>
          </td>
          <td>
            <%= order.status_i18n %>
          </td>
        </tr>
        <% end %>
        
      </table>
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
  <div class="container">
    <p>商品編集</p>
    
      <%= form_with model: @item ,url: admin_item_path, method: :patch do |f| %>
      <div class="form-group row justify-content-center">
          <%= f.label :商品画像 ,class: "col-sm-3" %>
          <div class="col-sm-8">
            <%= f.attachment_field :image %>
          </div> 
      </div>
    
      <div class="form-group row justify-content-center">
          <%= f.label :商品名 ,class: "col-sm-3" %>
          <div class="col-sm-8">
            <%= f.text_field :name, class: "form-control col-sm-8", placeholder: "商品名" %>
          </div>
      </div>
      
      <div class="form-group row justify-content-center">
          <%= f.label :商品説明 ,class: "col-sm-3" %>
          <div class="col-sm-8">
            <%= f.text_area :introduction, class: "form-control col-sm-8" , rows: "5", placeholder: "ここに説明文を記述します" %>
          </div> 
      </div>
      
    
      <div class="form-group row justify-content-center">
          <%= f.label :ジャンル ,class: "col-sm-3" %>
        <div class="col-sm-8">
          <%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "--選択してください--" %>

        </div>  
      </div>
      
    
      <div class="form-group row justify-content-center">
          <%= f.label :税抜価格 ,class: "col-sm-3" %>
          <div class="col-sm-8 d-inline-flex">
            <%= f.text_field :price, class: "form-control col-sm-8", placeholder: "1000" %><span>　円</span>
          </div>
      </div>
      
      
      <div class="form-group row justify-content-center">
          <%= f.label :販売ステータス ,class: "col-sm-3" %>
          <div class="col-sm-8">
            <div class="form_check form-check-inline">
              <label>
              <%= f.radio_button :is_active, 'true' %> <%= f.label :is_active, '販売中', value: true %>
              </label>
            </div>
            <div class="form_check form-check-inline">
              <label>
              <%= f.radio_button :is_active, 'false' %> <%= f.label :is_active, '販売停止', value: false %>
              </label>
            </div>
          </div> 
      </div>
      <div class="form-group row justify-content-center">
        <%= f.submit '変更を保存', class: "btn btn-success" %>
      </div>
      <% end %>

  </div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col"><p>商品一覧</p></div>
    <div class="col text-right"><a class="btn btn-outline-dark rounded-circle p-0" style="width:2rem;height:2rem;" href="/admin/items/new">＋</a></div>
  </div>
  <table class="table table-borderless">
    <thead class="table-light">
      <tr>
        <th scope="col">商品ID</th>
        <th scope="col">商品名</th>
        <th scope="col">税抜価格</th>
        <th scope="col">ジャンル</th>
        <th scope="col">ステータス</th>
      </tr>
    </thead>
    <% @items.each do |item| %>
    <tbody>
      <tr>
        <td>
          <%= item.id %>
        </td>
        <td>
          <%= link_to item.name, admin_item_path(item.id) %>
        </td>
        <td>
          <%= item.price.to_s(:delimited, delimiter: ',') %>
        </td>
        <td>
            <%= item.genre.name %>
        </td>
        <td>
          <% if item.is_active == true %>
            <span class="text-success">販売中</span>
            <% else %>
            <span class="text-secondary">販売停止中</span>
          <% end %>
        </td>
      </tr>

    </tbody>
    <% end %>
  </table>
  <%= paginate @items %>
  </div>

app/views/admin/items/new.html.erb
  <div class="container">
    <p>商品新規登録</p>
    
      <%= form_with model: @item ,url: '/admin/items', method: :post do |f| %>
      <div class="form-group row justify-content-center">
          <%= f.label :商品画像 ,class: "col-sm-3" %>
          <div class="col-sm-8">
            <%= f.attachment_field :image %>
          </div> 
      </div>
    
      <div class="form-group row justify-content-center">
          <%= f.label :商品名 ,class: "col-sm-3" %>
          <div class="col-sm-8">
            <%= f.text_field :name, class: "form-control col-sm-8", placeholder: "商品名" %>
          </div>
      </div>
      
      <div class="form-group row justify-content-center">
          <%= f.label :商品説明 ,class: "col-sm-3" %>
          <div class="col-sm-8">
            <%= f.text_area :introduction, class: "form-control col-sm-8" , rows: "5", placeholder: "ここに説明文を記述します" %>
          </div> 
      </div>
      
    
      <div class="form-group row justify-content-center">
          <%= f.label :ジャンル ,class: "col-sm-3" %>
        <div class="col-sm-8">
          <%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "--選択してください--" %>

        </div>  
      </div>
      
    
      <div class="form-group row justify-content-center">
          <%= f.label :税抜価格 ,class: "col-sm-3" %>
          <div class="col-sm-8 d-inline-flex">
            <%= f.text_field :price, class: "form-control col-sm-8", placeholder: "1000" %><span>　円</span>
          </div>
      </div>
      
      
      <div class="form-group row justify-content-center">
          <%= f.label :販売ステータス ,class: "col-sm-3" %>
          <div class="col-sm-8">
            <div class="form_check form-check-inline">
              <label>
              <%= f.radio_button :is_active, 'true' %> <%= f.label :is_active, '販売中', value: true %>
              </label>
            </div>
            <div class="form_check form-check-inline">
              <label>
              <%= f.radio_button :is_active, 'false' %> <%= f.label :is_active, '販売停止', value: false %>
              </label>
            </div>
          </div> 
      </div>
      <div class="form-group row justify-content-center">
        <%= f.submit '新規登録', class: "btn btn-success" %>
      </div>
      <% end %>

  </div>

app/views/admin/items/show.html.erb
<div class="container">
  
  <p>商品詳細</p>
  
    <div class="row">
      <div class="img-container col-sm-3">
        <%= attachment_image_tag @item, :image, format: 'jpeg' %>
      </div>
      
      <div class="col-sm-9">
        <table class="table table-borderless">
          
            <tr>
              <th scope="row">商品名</th>
              <td><%= @item.name %></td>
            </tr>
          
            <tr>
              <th scope="row">商品説明</th>
              <td><%= @item.introduction %></td>
            </tr>
          
          
            <tr>
              <th scope="row">ジャンル</th>
              <td><%= @item.genre.name %></td>
            </tr>

            <tr>
              <th scope="row">税込価格<br>(税抜価格)</th>
              <td><%= (@item.price*1.1).round.to_s(:delimited, delimiter: ',') %>（<%= @item.price.to_s(:delimited, delimiter: ',') %>）円</td>
            </tr>
  
            <tr>
              <th scope="row">販売ステータス</th>
                <% if @item.is_active == true %>
                  <td class="text-success">販売中</td>
                  <% else %>
                  <td class="text-secondary">販売停止中</td>
                <% end %>
            </tr>
          
            <td class="row justify-content-center">
              <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success" %>
            </td>
         
      </table>
      </div>
    </div>

</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <p>注文履歴詳細</p>
  <div class="row mt-3">
    <div class="col-3">
      <strong>購入者</strong>
    </div>
    <div class="col-8">
      <%= @order.customer.first_name+@order.customer.last_name %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-3">
      <strong>注文日</strong>
    </div>
    <div class="col-8">
      <%= @order.created_at.strftime('%Y/%m/%d') %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-3">
      <strong>配送先</strong>
    </div>
    <div class="col-8">
      <%= "〒"+@order.postal_code %> <%= @order.address %></br>
      <%= @order.name %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-3">
      <strong>支払方法</strong>
    </div>
    <div class="col-8">
      <%= @order.payment_method_i18n %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-3">
      <strong>注文ステータス</strong>
    </div>
    <div class="col-8">
          <%= form_with model: @order, url: admin_order_path(@order), method: :patch do |f| %> 
          <%= f.select :status , Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]}, class: "form-select" %>
          <%= f.submit '更新', class: "btn btn-success btn-sm ml-5" %>
          <% end %>
    </div>
  </div>
  <div class="row mt-3 position-relative">
    <div class="col-8">

    <table class="table-borderless col-12">
      <tr class="table-light">
        <th>商品名</th>
        <th>単価(税込)</th>
        <th>数量</th>
        <th>小計</th>
        <th>製作ステータス</th>
      </tr>
     <% @order_details.each do |order_detail| %>
      
        <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= order_detail.price %></td>
          <td><%= order_detail.amount %></td>
          <td><%= order_detail.price * order_detail.amount %></td>
          <td>
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %> 
            <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order.making_status.#{k}"), k]}, class: "form-select" %>

            <%= f.submit '更新', class: "btn btn-success btn-sm ml-5" %>
            <% end %>
          </td>
        </tr>
        
        <% @total += order_detail.price * order_detail.amount %>
      
    <% end %> 
    </table>

    </div>

    <div class="col-4 position-absolute bottom-0 end-0">

      <div class="row">

        <div class="col-6"><strong>商品合計</strong></div>
        
        <div class="col-4"><%= @total.to_s(:delimited, delimiter: ',') %>円</div>
      </div>
      <div class="row">
        <div class="col-6"><strong>送料</strong></div>
        <div class="col-4"><%= @order.shipping_cost.to_s(:delimited, delimiter: ',') %>円</div>
      </div>
      <div class="row">
      <div class="col-6"><strong>請求額合計</strong></div>
        <% @billing_total = 0 %>
        <% @billing_total = @total + @order.shipping_cost %>
        <div class="col-4"><strong><%= @billing_total.to_s(:delimited, delimiter: ',') %>円</strong></div>
      </div>

    </div>

  </div>
</div>

app/views/homes/about.html.erb
<div class="container text-center">
      <h1 class="my-5">About</h1>
      <p>ながのCAKEは全国発送可能なケーキ屋さんです。</p>
      <p>お子様からのお年寄りの方までお召し上がりいただけるよう、</p>
      <p>様々なバリエーションをご用意しております。</p>
      <p>また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。</p>
      <p>ぜひご注文ください。</p>

</div>