config/routes.rb
Rails.application.routes.draw do



# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  namespace :admin do
  resources :genres, :items, :customers, :orders, :order_details
  end
  
  get '/admin' => 'admin/homes#top'
  
    get '/orders/new' => 'public/orders#new', as: "orders_new"
    post '/orders/confirm' => 'public/orders#confirm', as: "orders_confirm"
    get '/orders/complete' => 'public/orders#complete', as: "orders_complete"
    get '/orders/:id' => 'public/orders#show', as: "orders_show"
    get '/orders' => 'public/orders#index', as: "orders_index"
    post '/orders' => 'public/orders#create', as: "orders_create"
    
    get '/cart_items' => 'public/cart_items#index'
    post '/cart_items' => 'public/cart_items#create'
    delete 'cart_items/:id' => 'public/cart_items#destroy', as: "destroy_cart_item"
    delete 'destroy_all' => 'public/cart_items#destroy_all', as: "destroy_all_cart_item"
    patch '/cart_items/:id' => 'public/cart_items#update', as: "update_cart_item"
    get '/items' => 'public/items#index'
    get '/items/:id' => 'public/items#show', as: "item_show"

    get '/addresses' => 'public/addresses#index'
    post '/addresses' => 'public/addresses#create'
    get '/addresses/:id/edit' => 'public/addresses#edit' ,as: "address"
    patch '/addresses/:id' => 'public/addresses#update', as: "update_address"
    delete '/addresses/:id' => 'public/addresses#destroy', as: "destroy_address"
  


  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'
  get '/customers/my_page' => 'public/customers#show', as: "my_page"
  get '/customers/information/edit' => 'public/customers#edit'
  patch '/customers/information' => 'public/customers#update'
  get '/customers/quit' => 'public/customers#quit'
  patch '/customers/out' => 'public/customers#out'

  
    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer, foreign_key: "customer_id"
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item, foreign_key: "item_id", optional: true
  belongs_to :customer, foreign_key: "customer_id", optional: true
  validates :amount, presence: true
  
def subtotal
    item.with_tax_price * amount
end



end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :addresses
  has_many :cart_items, dependent: :destroy
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :encrypted_password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :is_deleted, inclusion: {in: [true, false]}
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_one :item
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre, foreign_key: "genre_id", optional: true
  has_many :cart_items
  has_many :order_details
  attachment :image
  
 
  validates :image, presence: true
  validates :price, presence: true
  validates :genre_id, presence: true
  validates :is_active, inclusion: {in: [true, false]}
  
  def with_tax_price
      (price * 1.1).floor
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, foreign_key: "customer_id", optional: true
  has_many :order_details
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, finish_prepare: 4 }
 

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order, foreign_key: "order_id", optional: true
  belongs_to :item, foreign_key: "item_id", optional: true
  enum making_status: {
   production_not_possible: 0,
   production_pending: 1,
   in_production: 2,
   production_complete: 3
  }
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page]).per(8)
    @order_details = OrderDetail.all
    @subamount = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def index
    @items = Item.page(params[:page])
    
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#   before_action :configure_permitted_parameters, if: :devise_controller?
# before_action :authenticate_admin!, except: [:top, :about]
# before_action :authenticate_customer!, except: [:top, :about, :index]
#   protected

#   def configure_permitted_parameters
#     devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :encrypted_password, :address, :telephone_number, :is_deleted])
#   end

protected
  def after_sign_in_path_for(resource)
    if customer_signed_in?
        root_path
    else
      admin_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      admin_session_path
    else root_path
    end
  end

  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand navbar-light">
        <a class="navbar-brand" href="/">LOGO</a>
        <div class="ml-auto">
        <% if admin_signed_in? %>
          <% if request.fullpath.include? "/admin" %>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to "商品一覧", "/admin/items", class: "btn btn-outline-secondary mr-4" %>
              </li>
              <li class="nav-item">
                <%= link_to "会員一覧", "/admin/customers", class: "btn btn-outline-secondary mr-4" %>
              </li>
              <li class="nav-item">
                <%= link_to "注文履歴一覧", "/admin", class: "btn btn-outline-secondary mr-4" %>
              </li> 
              <li class="nav-item">
                <%= link_to "ジャンル一覧", "/admin/genres", class: "btn btn-outline-secondary mr-4" %>
              </li>
              <li class="nav-item">
                <%= button_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary mr-4" %>
              </li>
            </ul>
            <% else %>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to "マイページ", "/customers/my_page", class: "btn btn-outline-secondary mr-4" %>
              </li>
              <li class="nav-item">
                <%= link_to "商品一覧", "/items", class: "btn btn-outline-secondary mr-4" %>
              </li>
              <li class="nav-item">
                <%= link_to "カート", "/cart_items", class: "btn btn-outline-secondary mr-4" %>
              </li>    
              <li class="nav-item">
                
                <%= link_to 'ログアウト', destroy_customer_session_path, class: 'btn btn-outline-secondary mr-4', method: :delete %>
              </li>
            </ul>            
            <% end %>
          <% elsif customer_signed_in? %>
          
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "マイページ", "/customers/my_page", class: "btn btn-outline-secondary mr-4" %>
            </li>
            <li class="nav-item">
              <%= link_to "商品一覧", "/items", class: "btn btn-outline-secondary mr-4" %>
            </li>
            <li class="nav-item">
              <%= link_to "カート", "/cart_items", class: "btn btn-outline-secondary mr-4" %>
            </li>    
            <li class="nav-item">
              
              <%= link_to 'ログアウト', destroy_customer_session_path, class: 'btn btn-outline-secondary mr-4', method: :delete %>
            </li>
          </ul>
          
          <% else %>
          
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "About", "/about", class: "btn btn-outline-secondary mr-4" %>
            </li>
            <li class="nav-item">
              <%= link_to "商品一覧", "/items", class: "btn btn-outline-secondary mr-4" %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", "/customers/sign_up", class: "btn btn-outline-secondary mr-4" %>
            </li>    
            <li class="nav-item">
              <%= link_to "ログイン", "/customers/sign_in", class: "btn btn-outline-secondary mr-4" %>
            </li>
          </ul>
        <% end %>
        
          <ul class="navbar-nav mt-3">
            <li class="nav-item ml-auto">
            <form class="form-inline">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    <%= yield %>
    
  </body>
  <footer>
    
  </footer>
</html>